/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f407xx.h"

/*
 * PB14 --> SPI2_MISO
 * PB15 --> SPI2_MOSI
 * PB13 -> SPI2_SCLK
 * PB12 --> SPI2_NSS
 * ALT function mode : 5
 */

void SPI2_GPIOInit(void)
{
	GPIO_Handle_t SpiGpio;

	SpiGpio.pGPIOx = GPIOB;

	SpiGpio.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	SpiGpio.GPIO_PinConfig.GPIO_PinAltFunMode = 5;
	SpiGpio.GPIO_PinConfig.GPIO_PinOpType = GPIO_OP_TYPE_PP;
	SpiGpio.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	SpiGpio.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;

	//SCLK
	SpiGpio.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIO_Init(&SpiGpio);

	//MOSI
	SpiGpio.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;

}

void SPI2_Init(void)
{
	SPI_Handle_t SpiPin;

	SpiPin.pSPIx = SPI2;

	SpiPin.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
	SpiPin.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
	SpiPin.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV2;
	SpiPin.SPIConfig.SPI_DFF = SPI_DFF_8BITS;
	SpiPin.SPIConfig.SPI_CPOL = SPI_CPOL_HIGH;
	SpiPin.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
	SpiPin.SPIConfig.SPI_SSM = SPI_SSM_EN;

	SPI_Init(&SpiPin);

}



int main(void)
{
    char user_data[] = "Hello World";

    //Initialize GPIO pins to behave as SPI
    SPI2_GPIOInit();

    //Initialize SPI2 peripherals
    SPI2_Init();

    //To make NSS signal internally high to avoid MODF error
    SPI_SSIConfig(SPI2, ENABLE);

    //Enable SPI2 peripheral
    SPI_PeripheralControl(SPI2, ENABLE);

    //To send data
    SPI_SendData(SPI2, (uint8_t*)user_data, strlen(user_data));

    //To confirm SPI is not busy
    while(SPI_GetFlagStatus(SPI2, SPI_BUSY_FLAG));

    //Disable SPI2 peripheral
    SPI_PeripheralControl(SPI2, DISABLE);

    while(1);

    return 0;

}
